const cfg=await fetch('/api/projects?config=1',{cache:'no-store'}).then(r=>r.json());
const authMsg=document.querySelector('#authMsg');const app=document.querySelector('#app');const auth=document.querySelector('#auth');let token='';let selected=null;
function msg(el,text,cls='muted'){el.textContent=text;el.className=cls;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let firebase={};
if(cfg.firebase?.apiKey&&cfg.firebase?.authDomain&&cfg.firebase?.projectId&&cfg.firebase?.appId){const {initializeApp}=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js');const {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut}=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js');const appInstance=initializeApp(cfg.firebase);const authInstance=getAuth(appInstance);firebase={createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut,authInstance};}else msg(authMsg,'Customer authentication is not configured yet. Add the Firebase web configuration to enable accounts.','error');
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(path,{...options,headers});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d;}
async function refreshToken(user){token=user?await user.getIdToken():'';}
function renderProjects(items){const el=document.querySelector('#projects');if(!items.length){el.innerHTML='<p class="muted">No projects yet. Create your first project above.</p>';return;}el.innerHTML=items.map(p=>`<div class="project"><div><strong>${esc(p.projectName||'Unnamed project')}</strong><div class="muted">${esc(p.currentVersion||'0.1.0')} · ${esc(p.lifecycleState||'INTAKE')}</div></div><div class="row"><a class="button secondary" href="/?projectId=${encodeURIComponent(p.projectId)}">Open</a><button class="button secondary" data-project="${esc(p.projectId)}">Request change</button></div></div>`).join('');el.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{selected=items.find(p=>p.projectId===b.dataset.project);document.querySelector('#selected').classList.remove('hidden');document.querySelector('#selectedName').textContent=selected?.projectName||'Project';document.querySelector('#changeText').focus();});}
async function loadProjects(){const d=await api('/api/projects');renderProjects(d.projects||[]);}
if(firebase.onAuthStateChanged)firebase.onAuthStateChanged(async user=>{if(!user){token='';auth.classList.remove('hidden');app.classList.add('hidden');return;}await refreshToken(user);auth.classList.add('hidden');app.classList.remove('hidden');document.querySelector('#account').textContent=user.email||'Signed in';try{await loadProjects();}catch(e){msg(document.querySelector('#projects'),e.message,'error');}});
document.querySelector('#signin').onclick=async()=>{try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!firebase.signInWithEmailAndPassword)throw Error('Authentication is not configured');await firebase.signInWithEmailAndPassword(firebase.authInstance,email,password);msg(authMsg,'Signed in.','success');}catch(e){msg(authMsg,e.message,'error');}};
document.querySelector('#signup').onclick=async()=>{try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(password.length<6)throw Error('Use a password with at least 6 characters.');if(!firebase.createUserWithEmailAndPassword)throw Error('Authentication is not configured');await firebase.createUserWithEmailAndPassword(firebase.authInstance,email,password);msg(authMsg,'Account created.','success');}catch(e){msg(authMsg,e.message,'error');}};
document.querySelector('#signout').onclick=()=>firebase.signOut?.(firebase.authInstance);
document.querySelector('#create').onclick=async()=>{const n=document.querySelector('#projectName').value.trim(),b=document.querySelector('#brief').value.trim(),m=document.querySelector('#deliveryModel').value;try{if(!n||!b)throw Error('Project name and brief are required.');const d=await api('/api/projects',{method:'POST',body:JSON.stringify({action:'customer_create',projectName:n,brief:b,deliveryModel:m})});msg(document.querySelector('#createMsg'),'Project created.','success');window.location.href=`/?projectId=${encodeURIComponent(d.project.projectId)}`;}catch(e){msg(document.querySelector('#createMsg'),e.message,'error');}};
document.querySelector('#requestChange').onclick=async()=>{try{if(!selected)throw Error('Select a project first.');const text=document.querySelector('#changeText').value.trim();if(!text)throw Error('Describe the requested change.');await api('/api/projects',{method:'POST',body:JSON.stringify({action:'customer_action',projectId:selected.projectId,changeRequest:text})});msg(document.querySelector('#changeMsg'),'Change request sent to the factory.','success');document.querySelector('#changeText').value='';await loadProjects();}catch(e){msg(document.querySelector('#changeMsg'),e.message,'error');}};