const authMsg=document.querySelector('#authMsg');const app=document.querySelector('#app');const auth=document.querySelector('#auth');let token='';let selected=null;let firebase={};
function msg(el,text,cls='muted'){if(!el)return;el.textContent=text;el.className=cls;}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d;}
async function refreshToken(user){token=user?await user.getIdToken():'';}
function bind(id,handler){const el=document.querySelector(id);if(el)el.onclick=handler;}
function ensureAuthControls(){const password=document.querySelector('#password');if(password&&!document.querySelector('#togglePassword')){const wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:8px;align-items:center;margin-top:8px';password.style.marginTop='0';const btn=document.createElement('button');btn.type='button';btn.id='togglePassword';btn.className='authButton';btn.style.cssText='padding:9px 12px;white-space:nowrap';btn.textContent='Show password';btn.onclick=()=>{const showing=password.type==='text';password.type=showing?'password':'text';btn.textContent=showing?'Show password':'Hide password';};password.parentNode.insertBefore(wrap,password);wrap.appendChild(password);wrap.appendChild(btn);}const row=document.querySelector('#signin')?.parentElement;if(row&&!document.querySelector('#forgotPassword')){const b=document.createElement('button');b.id='forgotPassword';b.type='button';b.className='authButton';b.textContent='Forgot password?';b.style.cssText='margin-top:10px;width:100%';row.parentNode.insertBefore(b,row.nextSibling);}const grid=document.querySelector('.authGrid');if(grid){[['google','Continue with Google'],['apple','Continue with Apple'],['github','Continue with GitHub'],['microsoft','Continue with Microsoft']].forEach(([id,label])=>{if(!document.querySelector('#'+id)){const b=document.createElement('button');b.id=id;b.type='button';b.className='authButton';b.textContent=label;grid.appendChild(b);}});}}
async function socialSignIn(providerName){try{if(!firebase.signInWithPopup)throw Error('Authentication is not ready. Refresh the page and try again.');let provider;if(providerName==='google')provider=new firebase.GoogleAuthProvider();else if(providerName==='apple')provider=new firebase.OAuthProvider('apple.com');else if(providerName==='microsoft')provider=new firebase.OAuthProvider('microsoft.com');else if(providerName==='github')provider=new firebase.GithubAuthProvider();else throw Error('Unsupported sign-in provider');await firebase.signInWithPopup(firebase.authInstance,provider);}catch(e){msg(authMsg,e.code==='auth/popup-blocked'?'Please allow popups for this site.':(e.code==='auth/operation-not-allowed'?'This sign-in method is not enabled in Firebase yet.':e.code==='auth/account-exists-with-different-credential'?'An account already exists with another sign-in method. Sign in with that method first.':e.code==='auth/popup-closed-by-user'?'Sign-in was cancelled.':e.message),'error');}}
function renderProjects(items){const el=document.querySelector('#projects');if(!items.length){el.innerHTML='<p class="muted">No projects yet. Create your first project above.</p>';return;}el.innerHTML=items.map(p=>`<div class="project"><div><strong>${esc(p.projectName||'Unnamed project')}</strong><div class="muted">${esc(p.currentVersion||'0.1.0')} · ${esc(p.lifecycleState||'INTAKE')}</div></div><div class="row"><a class="button secondary" href="/?projectId=${encodeURIComponent(p.projectId)}">Open</a><button class="button secondary" data-project="${esc(p.projectId)}">Request change</button></div></div>`).join('');el.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{selected=items.find(p=>p.projectId===b.dataset.project);document.querySelector('#selected').classList.remove('hidden');document.querySelector('#selectedName').textContent=selected?.projectName||'Project';document.querySelector('#changeText').focus();});}
async function loadProjects(){const d=await api('/api/projects');renderProjects(d.projects||[]);}
async function initAuth(){try{ensureAuthControls();const cfg=await api('/api/projects?config=1');const c=cfg.firebase||{};if(!(c.apiKey&&c.authDomain&&c.projectId&&c.appId))throw Error('Customer authentication is not configured yet.');const [{initializeApp},{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,onAuthStateChanged,signOut,signInWithPopup,GoogleAuthProvider,OAuthProvider,GithubAuthProvider}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js')]);const appInstance=initializeApp(c);const authInstance=getAuth(appInstance);firebase={createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,onAuthStateChanged,signOut,signInWithPopup,GoogleAuthProvider,OAuthProvider,GithubAuthProvider,authInstance};onAuthStateChanged(authInstance,async user=>{if(!user){token='';auth.classList.remove('hidden');app.classList.add('hidden');return;}await refreshToken(user);auth.classList.add('hidden');app.classList.remove('hidden');document.querySelector('#account').textContent=user.email||'Signed in';try{await loadProjects();}catch(e){msg(document.querySelector('#projects'),e.message,'error');}});msg(authMsg,'Ready — choose a sign-in method.','muted');}catch(e){msg(authMsg,e.message,'error');}}
bind('#google',()=>socialSignIn('google'));bind('#apple',()=>socialSignIn('apple'));bind('#github',()=>socialSignIn('github'));bind('#microsoft',()=>socialSignIn('microsoft'));
bind('#signin',async()=>{try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!email||!password)throw Error('Enter your email and password.');if(!firebase.signInWithEmailAndPassword)throw Error('Authentication is still loading.');await firebase.signInWithEmailAndPassword(firebase.authInstance,email,password);}catch(e){msg(authMsg,e.code==='auth/invalid-credential'?'Email or password is incorrect.':e.code==='auth/too-many-requests'?'Too many attempts. Please wait and try again.':e.message,'error');}});
bind('#signup',async()=>{try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!email||!password)throw Error('Enter your email and password.');if(password.length<6)throw Error('Use a password with at least 6 characters.');if(!firebase.createUserWithEmailAndPassword)throw Error('Authentication is still loading.');await firebase.createUserWithEmailAndPassword(firebase.authInstance,email,password);}catch(e){msg(authMsg,e.code==='auth/email-already-in-use'?'An account already exists for this email.':e.code==='auth/operation-not-allowed'?'Email/password sign-in is not enabled in Firebase yet.':e.message,'error');}});
bind('#forgotPassword',async()=>{try{const email=document.querySelector('#email').value.trim();if(!email)throw Error('Enter your email first, then choose Forgot password.');if(!firebase.sendPasswordResetEmail)throw Error('Authentication is still loading.');await firebase.sendPasswordResetEmail(firebase.authInstance,email);msg(authMsg,'Password reset email sent. Check your inbox.','success');}catch(e){msg(authMsg,e.code==='auth/user-not-found'?'No account was found for that email.':e.code==='auth/invalid-email'?'Enter a valid email address.':e.code==='auth/too-many-requests'?'Too many requests. Please try again later.':e.message,'error');}});
bind('#signout',()=>firebase.signOut?.(firebase.authInstance));
bind('#create',async()=>{const n=document.querySelector('#projectName').value.trim(),b=document.querySelector('#brief').value.trim(),m=document.querySelector('#deliveryModel').value;try{if(!n||!b)throw Error('Project name and brief are required.');const d=await api('/api/projects',{method:'POST',body:JSON.stringify({action:'customer_create',projectName:n,brief:b,deliveryModel:m})});msg(document.querySelector('#createMsg'),'Project created.','success');window.location.href=`/?projectId=${encodeURIComponent(d.project.projectId)}`;}catch(e){msg(document.querySelector('#createMsg'),e.message,'error');}});
bind('#requestChange',async()=>{try{if(!selected)throw Error('Select a project first.');const text=document.querySelector('#changeText').value.trim();if(!text)throw Error('Describe the requested change.');await api('/api/projects',{method:'POST',body:JSON.stringify({action:'customer_action',projectId:selected.projectId,changeRequest:text})});msg(document.querySelector('#changeMsg'),'Change request sent to the factory.','success');document.querySelector('#changeText').value='';await loadProjects();}catch(e){msg(document.querySelector('#changeMsg'),e.message,'error');}});
initAuth();