const help={transfer:'Validated project package plus ownership handoff.',deploy:'Live deployment plus customer handoff.',managed:'Live deployment with ongoing maintenance and version tracking.'};
const esc=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);const projectId=params.get('projectId')||params.get('id');const customerId=params.get('customerId');let activeProjectId=projectId;const endpoint=projectId?`/api/projects?id=${encodeURIComponent(projectId)}`:customerId?`/api/projects?customerId=${encodeURIComponent(customerId)}`:'/api/projects';
const setText=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value??'—'};const setLink=(id,url)=>{const el=document.getElementById(id);if(!el)return;if(url){el.href=url;el.hidden=false}else el.hidden=true};function stateLabel(s){return String(s||'').replaceAll('_',' ')}const states=['INTAKE','BUILDING','VERIFYING','READY','DELIVERED'];
function timeline(state){const el=document.getElementById('timeline');if(!el)return;const current=states.indexOf(state);el.innerHTML=states.map((s,i)=>`<div class="${i<current?'done':i===current?'current':''}">${esc(stateLabel(s))}</div>`).join('')}
function progress(state){const i=Math.max(0,states.indexOf(state));const bar=document.getElementById('progressBar');if(bar)bar.style.width=`${Math.round(((i+1)/states.length)*100)}%`;setText('progressText',`${i+1} / ${states.length} lifecycle stages reached`)}
function statusClass(state){return state==='DELIVERED'||state==='READY'?'pill live':'pill'}
function history(p){const a=p.approvals||[],c=p.changeRequests||[];setText('approvalHistory',a.length?`Approvals: ${a.map(x=>`${x.decision} · ${x.version}`).join(' | ')}`:'No approvals recorded.');setText('changeHistory',c.length?`Change requests: ${c.map(x=>`${x.status} · ${x.request}`).join(' | ')}`:'No change requests recorded.')}
async function loadProject(){try{const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);const p=d.project||{};activeProjectId=p.projectId||activeProjectId;const v=p.verification||{},o=p.ownership||{},m=p.maintenance||{},state=String(p.lifecycleState||'INTAKE').toUpperCase();setText('status',stateLabel(state));const st=document.getElementById('status');if(st)st.className=statusClass(state);setText('projectName',p.projectName||'Unnamed project');setText('projectMeta',`Version ${p.currentVersion||'—'} · ${stateLabel(p.deliveryModel||'—')}`);setText('deliveryModel',stateLabel(p.deliveryModel||'—'));setText('modeHelp',help[p.deliveryModel]||'Factory delivery state.');setText('nextAction',p.nextCustomerAction||'No customer action recorded.');setText('qualityGate',v.qualityGate||'PENDING');setText('deployment',v.deployment||'PENDING');setText('healthCheck',v.healthCheck||'PENDING');setText('deliveryTitle',p.productionUrl?'Production delivery available':'Delivery evidence in progress');setText('deliveryEvidence',`Repository: ${p.repository||'PENDING'} · Hosting: ${p.hostingTarget||'PENDING'} · Production: ${p.productionUrl||'PENDING'}`);setText('repoOwnership',o.repository||'PENDING');setText('hostingOwnership',o.hosting||'PENDING');setText('handoffOwnership',o.handoff||'PENDING');setText('maintenanceStatus',m.status||'NOT_ENROLLED');setText('maintenanceVersion',`Current version: ${m.currentVersion||p.currentVersion||'—'}`);setText('recentChanges',m.recentChanges?.length?`Recent changes: ${m.recentChanges.join(', ')}`:'No recent changes recorded.');setText('projectId',p.projectId||'—');setText('brief',p.brief||'—');setLink('preview',p.previewUrl);setLink('production',p.productionUrl);setText('actionMessage',p.nextCustomerAction||'Actions are recorded against this project version.');progress(state);timeline(state);history(p);const pid=document.getElementById('p');if(pid&&!pid.value)pid.value=p.projectId||''}catch(e){setText('status','ERROR');const st=document.getElementById('status');if(st)st.className='pill';setText('projectName','Project unavailable');setText('projectMeta',e.message);setText('progressText','Unable to load Factory state')}}
async function postAction(payload){if(!activeProjectId)throw Error('Project is not loaded');const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,projectId:activeProjectId,version:(document.getElementById('projectMeta')?.textContent||'').split('·')[0].replace('Version ','').trim()})}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
const approvalForm=document.getElementById('approvalForm');if(approvalForm)approvalForm.addEventListener('submit',async e=>{e.preventDefault();try{const d=await postAction({action:'approve',decision:'APPROVED',comment:document.getElementById('approvalComment')?.value||''});setText('actionMessage','Approval recorded successfully.');history(d.project);await loadProject()}catch(err){setText('actionMessage',`Unable to record approval: ${err.message}`)}});
const changeForm=document.getElementById('changeRequestForm');if(changeForm)changeForm.addEventListener('submit',async e=>{e.preventDefault();try{const d=await postAction({action:'change_request',request:document.getElementById('changeRequest')?.value||''});setText('actionMessage','Change request recorded successfully.');history(d.project);await loadProject()}catch(err){setText('actionMessage',`Unable to record change request: ${err.message}`)}});
async function factoryCall(action){const key=document.getElementById('adminKey')?.value.trim(),pid=document.getElementById('p')?.value.trim()||activeProjectId;if(!key)throw Error('Founder admin key is required');if(!pid)throw Error('Project ID is required');const body={action,projectId:pid,startStep:Number(document.getElementById('startStep')?.value||1),endStep:Number(document.getElementById('endStep')?.value||10),outputTarget:document.getElementById('outputTarget')?.value||'web',instruction:document.getElementById('factoryInstruction')?.value.trim()||''};const r=await fetch('/api/factory',{method:'POST',headers:{'Content-Type':'application/json','X-Factory-Admin-Key':key},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function refreshFactory(){try{const key=document.getElementById('adminKey')?.value.trim(),pid=document.getElementById('p')?.value.trim()||activeProjectId;if(!key||!pid)throw Error('Project ID and founder admin key are required');const r=await fetch(`/api/factory?projectId=${encodeURIComponent(pid)}`,{headers:{'X-Factory-Admin-Key':key},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);setText('factoryResult',JSON.stringify(d.factory||d,null,2))}catch(e){setText('factoryResult',`ERROR: ${e.message}`)}}
const startFactory=document.getElementById('startFactory');if(startFactory)startFactory.addEventListener('click',async()=>{try{setText('factoryResult','Starting…');const d=await factoryCall('start');setText('factoryResult',JSON.stringify(d.factory||d,null,2));await loadProject()}catch(e){setText('factoryResult',`ERROR: ${e.message}`)}});const refreshFactoryBtn=document.getElementById('refreshFactory');if(refreshFactoryBtn)refreshFactoryBtn.addEventListener('click',refreshFactory);
loadProject();setInterval(loadProject,30000);