const help={transfer:'Validated project package plus ownership handoff.',deploy:'Live deployment plus customer handoff.',managed:'Live deployment with ongoing maintenance and version tracking.'};
const esc=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);const projectId=params.get('projectId')||params.get('id');const customerId=params.get('customerId');let activeProjectId=projectId;const endpoint=projectId?`/api/projects?id=${encodeURIComponent(projectId)}`:customerId?`/api/projects?customerId=${encodeURIComponent(customerId)}`:'/api/projects';
const setText=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value??'—'};const setLink=(id,url)=>{const el=document.getElementById(id);if(!el)return;if(url){el.href=url;el.hidden=false}else el.hidden=true};function stateLabel(s){return String(s||'').replaceAll('_',' ')}const states=['INTAKE','BUILDING','VERIFYING','READY','DELIVERED'];
function effectiveState(p,state){const v=p.verification||{};const ready=['PASSED','PASS','PASSED_OK'];return state==='READY'&&ready.includes(String(v.qualityGate).toUpperCase())&&ready.includes(String(v.deployment).toUpperCase())&&ready.includes(String(v.healthCheck).toUpperCase())?'DELIVERED':state}
function timeline(state){const el=document.getElementById('timeline');if(!el)return;const current=states.indexOf(state);el.innerHTML=states.map((s,i)=>`<div class="${i<current?'done':i===current?'current':''}">${esc(s==='DELIVERED'?'DELIVERED':stateLabel(s))}</div>`).join('')}
function progress(state){const i=Math.max(0,states.indexOf(state));const pct=Math.round(((i+1)/states.length)*100);const bar=document.getElementById('progressBar');if(bar)bar.style.width=`${pct}%`;setText('progressText',state==='DELIVERED'?'5 / 5 · Delivered':`${i+1} / ${states.length} · In progress`)}
function statusClass(state){return state==='DELIVERED'?'pill live':'pill'}
async function loadProject(){try{const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);const p=d.project||{};activeProjectId=p.projectId||activeProjectId;const v=p.verification||{},o=p.ownership||{},m=p.maintenance||{},rawState=String(p.lifecycleState||'INTAKE').toUpperCase(),state=effectiveState(p,rawState);setText('status',state==='DELIVERED'?'DELIVERED':stateLabel(state));const st=document.getElementById('status');if(st)st.className=statusClass(state);setText('projectName',p.projectName||'Unnamed project');setText('projectMeta',`Version ${p.currentVersion||'—'} · ${state==='DELIVERED'?'Production delivery':'Project delivery'}`);setText('deliveryModel',stateLabel(p.deliveryModel||'—'));setText('modeHelp',help[p.deliveryModel]||'Verified factory delivery.');setText('nextAction',state==='DELIVERED'?'No action needed — your project is live.':(p.nextCustomerAction||'The factory is completing delivery.'));setText('qualityGate',v.qualityGate||'PENDING');setText('deployment',v.deployment||'PENDING');setText('healthCheck',v.healthCheck||'PENDING');setText('deliveryTitle',state==='DELIVERED'?'Your project is ready':'Project delivery in progress');setText('deliveryEvidence',p.productionUrl?`Live and healthy · ${p.productionUrl}`:'Production URL will appear when deployment is ready.');setText('repoOwnership',o.repository||'READY');setText('hostingOwnership',o.hosting||'CONNECTED');setText('handoffOwnership',o.handoff||'READY');setText('maintenanceVersion',`Version ${m.currentVersion||p.currentVersion||'—'}`);setText('projectId',p.projectId||'—');setText('brief',p.brief||'');setLink('production',p.productionUrl);progress(state);timeline(state)}catch(e){setText('status','ERROR');const st=document.getElementById('status');if(st)st.className='pill';setText('projectName','Project unavailable');setText('projectMeta',e.message);setText('progressText','Unable to load project state')}}
async function factoryCall(action){const key=document.getElementById('adminKey')?.value.trim(),pid=activeProjectId;if(!key)throw Error('Founder admin key is required');if(!pid)throw Error('Project is not loaded');const body={action,projectId:pid,startStep:Number(document.getElementById('startStep')?.value||1),endStep:Number(document.getElementById('endStep')?.value||10),outputTarget:document.getElementById('outputTarget')?.value||'web',instruction:document.getElementById('factoryInstruction')?.value.trim()||''};const r=await fetch('/api/factory',{method:'POST',headers:{'Content-Type':'application/json','X-Factory-Admin-Key':key},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function refreshFactory(){try{const key=document.getElementById('adminKey')?.value.trim();if(!key||!activeProjectId)throw Error('Founder admin key is required');const r=await fetch(`/api/factory?projectId=${encodeURIComponent(activeProjectId)}`,{headers:{'X-Factory-Admin-Key':key},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);setText('factoryResult',JSON.stringify(d.factory||d,null,2))}catch(e){setText('factoryResult',`ERROR: ${e.message}`)}}
const startFactory=document.getElementById('startFactory');if(startFactory)startFactory.addEventListener('click',async()=>{try{setText('factoryResult','Starting…');const d=await factoryCall('start');setText('factoryResult',JSON.stringify(d.factory||d,null,2));await loadProject()}catch(e){setText('factoryResult',`ERROR: ${e.message}`)}});const refreshFactoryBtn=document.getElementById('refreshFactory');if(refreshFactoryBtn)refreshFactoryBtn.addEventListener('click',refreshFactory);
loadProject();setInterval(loadProject,30000);